### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by Silex**
Hello,

**DO NOT MERGE THIS !**

This is the start of a discussion about supporting docker, with an example Dockerfile. If you want to go this route, the following steps will follow:

- README examples with docker compose workflows
- Github actions that automatically build & push the docker image to some registry everytime to commit/tag to this repo.

Does the Dockerfile looks correct? you just `bun run build` then copy `dist/index.js` to the correct folder in order to serve it?

### CODE REVIEW

**Comment by reyzzz** [comment]
The dockerfile seems to be correct, but in order for quasaScale backend to work in docker, a couple changes should be made.
I will look at it.

**Comment by Silex** [comment]
It works fine by me with this Dockerfile:

``` Dockerfile
FROM oven/bun:latest

WORKDIR /usr/src/app

RUN apt update -y && apt install -y curl unzip
RUN curl -fsSL https://get.docker.com | sh
RUN mkdir -p /tmp/quasascale-backend && \
    cd /tmp/quasascale-backend && \
    curl -fsSLO https://github.com/reyzzz/quasaScale-backend/releases/download/v0.23.0-beta.2/quasascale-backend.zip && \
    unzip quasascale-backend.zip && \
    mv index.js /usr/src/app && \
    rm -r /tmp/quasascale-backend

USER bun
ENTRYPOINT [ "bun", "run", "index.js" ]
```

Along with this docker-compose:

``` yaml
  quasascale-backend:
    build: 'quasascale/backend'
    restart: 'always'
    volumes:
      - './data/headscale/config:/etc/headscale'
      - './data/headscale/database:/var/lib/headscale'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      HEADSCALE_TOKEN: 'xxxx'
      HEADSCALE_CONFIG_PATH: '/etc/headscale/config.yaml'
      HEADSCALE_SQLITE_PATH: '/var/lib/headscale/db.sqlite'
      HEADSCALE_ACL_PATH: '/var/lib/headscale/acl.hujson'
      HEADSCALE_API_URL: 'https://connect.mydomain.com/api/v1'
      QUASASCALE_URL: 'https://quasa.connectmydomain.com'
      CONTAINER_NAME: 'headscale'
      DOCKER: 'true'
      PORT: '80'
```

Tho users management seems to fail, but I need to check why.

The dockerfile above is to automate the releases so it does not need to go through the unzip mess and builds from source directly.

What do you think needs to be done in the backend for it to work with docker?

**Comment by reyzzz** [comment]
Looking at how you mounted the volumes seems indeed to be working and no need for changes, but I noticed one thing HEADSCALE_API_URL should be the http localhost url so you don't get any cors issue from headscale and maybe in this case if both containers are on the same docker network you can have the ip address of headscale docker.

**Comment by Silex** [comment]
`QUASASCALE_URL` should also be renamed to `QUASASCALE_URLS` I think

**Comment by reyzzz** [comment]
I was rethinking what I said earlier, so when quasaScale  backend is running in a docker container, it will no be able to get the version of headscale therefore we won't be able to add this quasaScale backend instance to the frontend. So this needs definitely a fix.

**Comment by Silex** [comment]
I don't get it because in my example it does get the version from headscale, and both the frontend and backend run in a container (as well as headscale), with a traefik proxy in front...

**Comment by Silex** [comment]
@reyzzz this is more or less ready, right now it only builds when you push a tag, and reuses that tag for the docker image.

So if your secret `DOCKER_USERNAME` is `reyzzz` and you push tag `1.0` you'll get image `reyzzz/quasascale-backend:1.0`.

But maybe this approach is not the best one and it's preferable to build every night all tags? that way handling tag "latest" is easier.

**Comment by Silex** [comment]
Also your current tags are a bit weird, why reuse "v0.23.0" from headscale?

**Comment by reyzzz** [comment]
I am using the same version as headscale to prevent having problems when/if headscale implements some breaking changes, so that quasaScale users would automatically know which version is compatible with headscale.

If you have a better idea, I am open for suggestions.

**Comment by Silex** [comment]
The problem with this approach is that there'll be no quasascale version. How do you tell what is the quasascale version?

We can imagine something like `v0.23.0-1.0.0` where the `1.0.0` is the quasascale version, then you can have `1.0.1` `1.0.2` for bugfixes, `1.1.0` or `1.2.0` for minor version and `2.0.0` etc for major versions (https://semver.org)...

But let's address the elephant in the room: what if headscale 0.24.0 is actually 100% compatible with quasascale? it'd be silly to create a quasascale 0.24.0 version that is the exact same as 0.23.0.

I don't think users need to know which version is compatible with headscale, instead you create an entry in the README for that and you check _in the code_ what headscale version is there and you throw an error if an incompatible version is detected.

Or better, you adapt to each headscale version.

**Comment by reyzzz** [comment]
I know about semantic versioning, if we want to use it we need to opt out of headscale version.

Maybe as you suggested, check in the code for headscale compatibility. 

This seems to be the best approach.

**Comment by Silex** [comment]
Yes, you start by querying the version then you instantiate a different headscale engine... but my guess is that currently you don't have that problem because you only support 0.23.0, you only fear 0.24.0 might be different.

Don't let fears dictate design, adapt to known changes instead :-)

**Comment by reyzzz** [comment]
😁 It's not about fear, rather about maintaining backwards compatibility. But I guess I don't need it even. Whenever there is a breaking change with headscale, quasaScale will get an update too and the new quasaScale version must not be backwards compatible.
I think, it is not a bad approach.

**Comment by Silex** [comment]
On a side note I was thinking: would it make sense to rename quasacale to quasascale-frontend?

That way images would be like:

- reyzzz/quasascale-backend:1.0.0
- reyzzz/quasascale-frontend:1.0.3

**Comment by Silex** [comment]
And docker-compose would look like:

``` yaml
services:
  headscale:
    image: 'headscale/headscale:0.23.0'
    container_name: 'headscale'
    restart: 'always'
    command: 'serve'
    environment:
      TZ: 'Europe/Zurich'
    volumes:
      - './data/headscale/config:/etc/headscale'
      - './data/headscale/database:/var/lib/headscale'

  quasascale-frontend:
    image: 'reyzzz/quasascale-frontend:latest'
    restart: 'always'
    environment:
      PORT: '80'

  quasascale-backend:
    image: 'reyzzz/quasascale-backend:latest'
    restart: 'always'
    volumes:
      - './data/headscale/config:/etc/headscale'
      - './data/headscale/database:/var/lib/headscale'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      HEADSCALE_TOKEN: '1234'
      HEADSCALE_CONFIG_PATH: '/etc/headscale/config.yaml'
      HEADSCALE_SQLITE_PATH: '/var/lib/headscale/db.sqlite'
      HEADSCALE_ACL_PATH: '/var/lib/headscale/acl.hujson'
      HEADSCALE_API_URL: 'https://connect.stvs.com/api/v1'
      QUASASCALE_URL: 'https://quasa.connect.stvs.com'
      CONTAINER_NAME: 'headscale'
      DOCKER: 'true'
      PORT: '80'
```

**Comment by Silex** [comment]
Also, overall I wonder if there's really value in separating the backend & the frontend, but I didn't give it a lot of thoughts.

The idea is so people could write their own UI based on the backend if they don't want the current frontend?

**Comment by reyzzz** [comment]
The value of separating them, is to be able to manage multiple headscale/quasaScale-backend from one frontend, nevertheless you must not host the frontend on the same machine/server, rather you have the option doing it. That's why I once mentioned in a comment that I was thinking about hosting it, so everyone would use it without the need of hosting it themselves. 

As for renaming the frontend to quasascale-frontend, it seems to be a good idea too. The naming in this form is more straightforward.

**Comment by Silex** [comment]
> That's why I once mentioned in a comment that I was thinking about hosting it, so everyone would use it without the need of hosting it themselves.

Ah I get it, thanks.

Is there a way to pre-fill the backend & API key in the frontend? I plan on adding some authentification prior to reaching the frontend (e.g basic auth), so once users are logged then can use quasascale-frontend. It's a bit annoying that each users has to fill in a backend & API key for their browser.

**Comment by reyzzz** [comment]
I can provide an export/import so whenever you change browser or device you just need to import the data once and you have all your instances ready to manage.

**Comment by reyzzz** [comment]
I still don't get it. Why would need a basic authentication?
The quasascsle frontend can do nothing without headscale API key and quasaScale backend url. Therefore I don't see the point of putting any kind of authentication. If you are thinking of security, I would say if someone was able to get your headscale API key it would be definitely easy for him to get the basic auth.

If I would implement some kind of login, we would need a third project to offer the user management and everything around it.

If we call the project quasascale-manager, this would need to be hosted once (like the frontend) and it will be managing all your users independent from quasascale-backend but taking it into consideration.

**Comment by Silex** [comment]
Ok you can merge this.

**Pull request merged**
