### PR TITLE
Fix docker images

### PR DESCRIPTION
**Pull request by Silex**
Hello,

As always, code that is not tested does not work :-)

Please merge this, and create `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`.

Right now it works like this:

- main branch is built using tag "main"
- all tags are built & pushed with:
  - vX.Y.Z
  - X.Y.Z
  - latest

That way the latest tag pushed has the latest tag, keep that in mind if you have to re-push old tags (just repush the latest tag after).

### CODE REVIEW

**Comment by Silex** [comment]
It looks like this (v1.2.3 is an example tag): https://hub.docker.com/repository/docker/silex/quasascale-backend/tags

The cache image is the cache for the main image, to speed up builds. Tags don't need a cache as they are built only once.

Now that I said that maybe we should rebuild all tags periodically so the base image gets updated 😅

I'll add commits to the PR hold on. I'll make a cron that builds all tags once per day, and for main it happens on pushes.

**Comment by reyzzz** [comment]
Hello,

I don't like the idea of building an image daily for no reason. We should only build on new commits on main or on creation of a release.

**Comment by Silex** [comment]
Ok you can merge.

It builds & push all tags at midnight, and the main branch each time you push.

We have many options, like:
- Build & push all branches on each push.
- Build all branches, but only push main.
- Build all branches, but never push (some sort of "docker-ci" for PRs).

Tell me if you want to pick one of them instead of the current setup.

**Comment by Silex** [comment]
> I don't like the idea of building an image daily for no reason. We should only build on new commits on main or on creation of a release

No, it only builds the tags daily _if the main image changed_ (the one it's based on, here `bun:latest`). Otherwise it stays the same.

**Comment by Silex** [comment]
(you want to rebuild if the base image changed, otherwise your images will have security issues)

**Pull request merged**
